# Inspired by:
# https://github.com/zopefoundation/meta/tree/master/config/pure-python
name: tests

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "23 5 * * wed"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          # [Python version, tox env]
          - ["3.6", "py36-Plone52"]
          - ["3.7", "py37-Plone52"]
          - ["3.8", "py38-Plone52"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.config[0] }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config[0] }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            eggs
          key: ${{ runner.os }}-pip-${{ matrix.config[0] }}-${{ hashFiles('setup.*', 'tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.config[0] }}-
            ${{ runner.os }}-pip-
      - name: Pre commit
        uses: pre-commit/action@v2.0.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Run tox
        run: tox -e ${{ matrix.config[1] }}
